### ISSUE TITLE
KafkaConsumer is not safe for multi-threaded access

### ISSUE THREAD

**Issue by nilportugues** [com-nilportugues/eventbus-kafka-json#4]
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1800)
        at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:1784)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1091)
        at com.nilportugues.eventbus.kafka.json.KafkaJsonEventConsumer.lambda$consume$0(KafkaJsonEventConsumer.java:31)

**Comment by nilportugues** [comment]
https://stackoverflow.com/questions/36274024/how-to-use-multi-thread-consumer-in-kafka-0-9-0
